---
apiVersion: v1
kind: Pod
metadata:
  name: thread-yield-test-runc
  labels:
    app: thread-yield-test-runc
spec:
  runtimeClassName: runc
  restartPolicy: Never
  containers:
    - name: test
      image: evanfoster/kata-java-benchmarks:thread-yield-test
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 8
          memory: 8Gi
        requests:
          cpu: 8
          memory: 8Gi
  dnsPolicy: Default
