---
apiVersion: v1
kind: Pod
metadata:
  name: thread-creation-teardown-test-kata
  labels:
    app: thread-creation-teardown-test-kata
spec:
  tolerations:
    - key: "node.kubernetes.io/kata-containers"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    node.kubernetes.io/kata-containers: "true"
  runtimeClassName: kata-qemu
  restartPolicy: Never
  containers:
    - name: test
      image: evanfoster/kata-java-benchmarks:thread-creation-teardown-test
      imagePullPolicy: Always
      env:
        - name: javaargs
          value: "-Druntime=15 -Dwarmup=5"
      resources:
        limits:
          cpu: 1
          memory: 8Gi
        requests:
          cpu: 1
          memory: 8Gi
  dnsPolicy: Default
